name: Build SmartChatix APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install dependencies
      run: npm ci

    - name: Setup Expo CLI
      run: npm install -g @expo/cli

    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: Create app.json if not exists
      run: |
        if [ ! -f app.json ]; then
          echo '{
            "expo": {
              "name": "SmartChatix",
              "slug": "smartchatix",
              "version": "1.0.0",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "userInterfaceStyle": "light",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "assetBundlePatterns": [
                "**/*"
              ],
              "ios": {
                "supportsTablet": true
              },
              "android": {
                "adaptiveIcon": {
                  "foregroundImage": "./assets/adaptive-icon.png",
                  "backgroundColor": "#FFFFFF"
                },
                "package": "com.smartchatix.app"
              },
              "web": {
                "favicon": "./assets/favicon.png"
              }
            }
          }' > app.json
        fi

    - name: Prebuild for Android
      run: npx expo prebuild --platform android --clean

    - name: Enable cleartext traffic for HTTP
      run: |
        sed -i 's/android:enableOnBackInvokedCallback="false"/android:enableOnBackInvokedCallback="false" android:usesCleartextTraffic="true"/g' android/app/src/main/AndroidManifest.xml

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartChatix-APK-v2
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: SmartChatix v1.0.${{ github.run_number }}
        body: |
          🚀 SmartChatix Native App
          📱 APK lista para instalar en Android

          **Características:**
          - ✅ Interfaz nativa móvil
          - ✅ Optimizada para Android
          - ✅ Gestos touch nativos

          **Instalación:**
          1. Descarga el APK
          2. Activa "Fuentes desconocidas" en Android
          3. Instala la app
          4. ¡Disfruta SmartChatix nativo!
        files: android/app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false